version: '2'
services:
   db:
     restart: always
     image: postgres:9.6
     environment:
       - POSTGRES_USER=bwafc
       - POSTGRES_PASSWORD=linijka
       - POSTGRES_DB=scrapy2
   web:
     build: galeria
     command: python /app/rest/manage.py runserver
     volumes:
        - .:/app
     ports:
       - "8080:8080"
     links:
       - db
