version: '2'
services:
  db:
    restart: always
    image: postgres:9.6 
    environment:
      - POSTGRES_USER=bwafc
      - POSTGRES_PASSOWRD=linijka
      - POSTGRES_DB=scrapy2
    ports:
      - "5432:5432"
  scraper:
    build: ./galeria
    volumes:
      - .:/app
    links:
      - db
